language: python

notifications:
  email: false

python:
  - 2.7
  - 3.5

install:
  - pip install tox-travis
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-flake8
  - pip install .

script:
  - tox

after_success:
  - coveralls
